name: Githubblog

on:
  workflow_dispatch:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Onionsite Pull Webhook
        uses: jasongitmail/fast-webhook@v1
        with:
          url: ${{ secrets.ONION_WEBHOOK_URL }}
          json: '{}'
